name: Deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Copy Files
      run: rsync -a /root/actions-runner/_work/dc-bknd/dc-bknd /var/www/dcapi/
      
    - name: Install Depencdencies
      run: npm install --prefix /var/www/dcapi
    
    - name: Give Permission
      run: chmod -R 775 /var/www/dcapi/


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
